### ISSUE TITLE
Sortable listview column arrows don't render correctly on OS3

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#334]
When creating a column that has the `SORTABLE` tag set, a black filled rectangle appears in the column header on OS3. Shouldn't that be an arrow instead?

![shot](https://user-images.githubusercontent.com/6772528/118515370-9e2f9400-b735-11eb-82e0-cc749bff4f61.jpg)

**Comment by tboeckel** [comment]
Of course there should be an arrow indicating the current sort order. The image file MUI:Images/list_Sort.mim must exist, be handable by datatypes.library and contain both the up and down arrow image. If loading the image fails for any reason MUI falls back to that simple black rectangle.

The PNG image is contained in each an every release archive and will be installed by the Installer script.

So, either the user's system doesn't have a suitable PNG datatype installed or the user simply skipped the installation of the image or the user deleted it afterwards.

**Comment by softwarefailure** [comment]
> If the alpha channel is not handled properly then you get the typical magenta background, not just a Black rectangle.

Well, but MultiView also shows it as a black rectangle (see screenshot below).

> What about all the other PNG images? How are these displayed by MUI?

Are the icons in the MUI prefs PNG images? They are rendered correctly. See screenshot:

![Ohne Titel-2](https://user-images.githubusercontent.com/6772528/118844772-8722aa80-b8cb-11eb-9c2a-1a15486d9f49.png)

**Comment by tboeckel** [comment]
No, these are embedded images. Try the 'Images' page.

**Comment by softwarefailure** [comment]
Ok, not all images on the Images page look correct, e.g. the tokai ones don't, cf.:

![Ohne Titel-2](https://user-images.githubusercontent.com/6772528/118860847-2485da80-b8dc-11eb-9e26-22c93ad425eb.png)

**Comment by tboeckel** [comment]
It all boils down to the fact, that the default PNG datatype of AmigaOS3 does not handle transparency correctly. This can be worked around by 3rd party PNG datatypes.

A possible MUI based fix would be to not use an external PNG image for the sorting arrow images, but to use an internal vector image instead (image spec 1:22 and 1:23). Alternatively I could set a user definable up/down arrow image (6:38 and 6:39). I think the latter would be the best approach. That way the user can even define his/her preferred images.

But the datatypes issue with PNG image remains nevertheless and might pop up all over the place over and over again. If an application uses custom PNG images with transparency then the user MUST have a proper PNG datatype installed. The default one of AmigaOS3 is simply broken. Period.

**Comment by tboeckel** [comment]
Fixed in the next nightly build. From now on the user configurable tape up/down images will be used.

**Comment by softwarefailure** [comment]
Thanks, but where can I download the latest nightly build? On http://nightly.muidev.de I cannot find anything newer than 21st April 2021.

**Comment by jens-maus** [comment]
> Thanks, but where can I download the latest nightly build? On http://nightly.muidev.de I cannot find anything newer than 21st April 2021.

Still on my TODO list to port the nightly build stuff over to GitHub...

**Comment by softwarefailure** [comment]
Well, you better hurry up with that because the latest available nightly builds will time out tomorrow...

**Comment by jens-maus** [comment]
@softwarefailure Here you go: https://github.com/amiga-mui/muidev/releases/tag/snapshots

**Comment by supernobby** [comment]
Hello! On my Amiga 4000 I use MUI 5.0 (20210831), where this change should be included. But can you please tell me, how to configure MUI to use the build-in image?
I ask, because the program "Luciferin" (FlashRom Tool for Deneb) is, according to SnoopDos, still looking for a file called "MUI:Images/list_Sort.mim". As it can't find one, there is no symbol in the "File Borwser" list, where the sort option is in the "Name" column.
So I wonder, how this is supposed to work, unless the Luciferin program does nothing worng.
Or did I miss something. Thanks.

**Comment by supernobby** [comment]
Just to add. I tried some MUI demo programs. There is "List1" and "List2", where the sort symbol is visible.
But there is also "MultiSel", which shows the same problem as the Luciferin program. "MultiSel" demo will also look for "MUI:Images/list_Sort.mim" and as there is none, there is an empty box in the list header.

**Comment by tboeckel** [comment]
As already pointed out above List class no longer uses MUI:Images/list_Sort.mim, because the default AmigaOS3 PNG DataType does not handle transparency correctly. Instead the up/down images are used. These must be configured in MUI prefs on the Images page (see screenshot)

![muiprefs](https://user-images.githubusercontent.com/13648670/215415658-47627e21-1119-45ba-9fc6-a27d77fafcf0.png)

**Comment by supernobby** [comment]
Hi thanks for the reply. I see these up and down arrows in the settings.
But can you please try the "MultiSel" Demo from the MUI Demo programs folder to see what you get? In my case, there is no such arrow visible. Thank you!

**Comment by tboeckel** [comment]
Works for me
![multisel](https://user-images.githubusercontent.com/13648670/217189653-422fc817-4491-4c51-972b-354972fcb9c0.jpg)

**Comment by supernobby** [comment]
Thanks for testing. But do you have MUI:Images/list_Sort.mim available? Can you please check with SnoopDos if MultiSel is looking for that file? I don't have that file and I get nothing there where. And SnoopDos shows, MultiSel is looking for it.

**Comment by tboeckel** [comment]
Yes, I have. The MultiSel demo uses Dirlist class and this one still explicitly uses that image. If I remove/rename it then I also just get a grey block instead of an arrow image. But this is the only occurence in the whole source code. The List1/2 demo apps no longer rely on external images to indicate the column sort order.

On the other hand list_Sort.mim is definitely part of the release archive. So if it is missing on your system simply grab from the archive.

**Comment by supernobby** [comment]
Could the Dirlist class also be made to use the internal image, as we have these up/down arrows now? And Dirlist class probably also suffers from the same problem this whole issue was opend for.

**Comment by tboeckel** [comment]
The next nightly build's Dirlist class will use the same indicator images as List class.
