### ISSUE TITLE
Where are the downloads?

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#335]
Since http://muidev.de has been shutdown, I can't find any binary packages for download any more. Where are they?

**Comment by samo79** [comment]
I wonder why the hell Jens decided to switch this project to github.. it is inconvenient, useless since MUI is not open source.. and it neither works with Odyssey!
The old site worked perfectly, it was fast and easy to use with an excellent bug reporting system, an history of the versions, the nightly build releases etc ..

**Comment by tboeckel** [comment]
The old web pages might have worked with old and outdated browsers, but it is more than a PITA to keep the backend running on modern systems. trac heavily relies on python2, which is deprecated for a long time already, and it is no longer really actively maintained. Remember the more or less regular "bad gateway" errors? These always happened, when the hosting Linux system updated one of its components and broke the fragile trac system which could only be repaired manually with a lot of work.

**Comment by jens-maus** [comment]
@samo79 
> I wonder why the hell Jens decided to switch this project to github.. it is inconvenient, useless since MUI is not open source.. and it neither works with Odyssey!

GitHub is a standard development platform these days and just because you can't see the private MUI source code repo here doesn't mean Thore&me are just using GitHub for the user-end pages. And don't blame GitHub and the modern world for AmigaOS applications not being able to keep up with modern technology. GitHub is state-of-the-art in software development these days and with its integrated CI/CD possibilities it help a lot!

> The old site worked perfectly, it was fast and easy to use with an excellent bug reporting system, an history of the versions, the nightly build releases etc ..

Well, the old bug items are ported to GitHub and are there, the old versions and nightly build releases will sooner or later come back here! To say it in common AmigaOS terms: "Just two more weeks!" :)

**Comment by jens-maus** [comment]
Ok, it just took me 14 hours and not two weeks:
https://github.com/amiga-mui/muidev/releases

Enjoy :)
