### ISSUE TITLE
Group frame isn't drawn for root object

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#341]
For some reason MUI doesn't seem to draw the group frame correctly when that group is the root object of the window. See the attached demo program.
[main.txt](https://github.com/amiga-mui/muidev/files/6587009/main.txt)

**Comment by tboeckel** [comment]
The reason is that this frame is user configurable. Just modify the frame setting of Windows/Background/Window. Any custom frame setting will be overridden while opening the window.
How does MorphOS MUI handle this situation?
Of course I can change this behavior to apply the user setting if and only if the root object has no custom frame set.

**Comment by tboeckel** [comment]
Fixed in the next nightly build. The user configurable window frame will be applied only if the root object as no custom frame set.
