### ISSUE TITLE
Remove the silly timeout feature

### ISSUE THREAD

**Issue by softwarefailure** [amiga-mui/muidev#343]
I've said it before, I'll say it again: The fact that nightly releases time out after 4 weeks must be one of the silliest features ever imagined. When checking if something worked with earlier nightlies and got broken later, I always have to set the clock back in order to use those older nightlies. With the migration to github things have gotten worse because nightlies seem only to be built sporadically now. As of today (July 10th), the most recent nightly is from June 8th, which is over 4 weeks old now and of course that nightly won't run without setting the clock back.

Seriously, this "feature" is utter nonsense and should be removed immediately (and the person who came up with that "great idea" should be publically tarred and feathered)

$0.02

**Comment by tboeckel** [comment]
Thanks for the offer to be tarred and feathered... It was both Jens' and my idea.

**Comment by tboeckel** [comment]
From the next nightly build on the "MUI has expired" requester will have a second answer button to allow continue using the outdated nightly build.

**Comment by jens-maus** [comment]
> From the next nightly build on the "MUI has expired" requester will have a second answer button to allow continue using the outdated nightly build.

@tboeckel I would also suggest to completely remove that whole expiration handling similar to how I recently did for YAM. All this was added at a time where Amiga development was still fun and with an active developer/tester community so that we were protected from non-sense bug reports of lazy ppl continuing to use old versions. Now that the community has vanished and the Amiga platform can anyway be considered a dead platform, I think it is worthwhile to consider removing this expiration altogether and let them all use rotten versions, if they wish to :)

**Comment by tkurbad** [comment]
@jens-maus While I dislike the wording of @softwarefailure regarding the tar-and-feather-suggestion, but instead am very grateful that there are people still dedicating so much time and effort towards the Amiga, I also don't like the aminet approach of irreversibly replacing older versions with new ones, which this expiration requester perfectly emulates.
This project is among the bright examples in Amigaland that keep a clean track record of commits and fixes and has a comprehensible versioning scheme.
And while I like fresh and bugfixed software, sometimes it's nice to have the ability to move one (or several) steps backwards. This is even more important on a retro platform, where it's sometimes hard to distinguish between a sudden hardware failure and a software regression.
