### ISSUE TITLE
Hyperlink behaves strangely after setting MUIA_Hyperlink_URI

### ISSUE THREAD

**Issue by afalkenhahn** [amiga-mui/muidev#355]
Take a look at the attached demo program. You need to press the button and then resize the window (sometimes you need to resize the window multiple times). Then there'll often be glitches in the two hyperlink gadgets. For example, they'll look like this:
![shot](https://user-images.githubusercontent.com/6772528/136698867-457cc5fc-4c7e-41ac-a7e6-4a728d5b66da.png)

or like this
![shot2](https://user-images.githubusercontent.com/6772528/136698870-49ab7710-2def-4ed0-8137-728b0b28a03f.png)

It doesn't happen every time but after a few attempts it usually shows so there must be something wrong.

Tested with the latest release from August 31 on OS3.

[main.txt](https://github.com/amiga-mui/muidev/files/7317541/main.txt)

**Comment by tboeckel** [comment]
Fixed in the next nightly build.
`* mcc/Hyperlink.c: changing the URI of a Hyperlink object without special text
    via MUIA_Text_Contents now also correctly updates the displayed text when
    MUIA_Hyperlink_URI is changed via OM_SET. Before the previous and now
    invalid text pointer was still used for the display of the link. This closes
    #355.
[Hyperlink_21.33_os3.zip](https://github.com/amiga-mui/muidev/files/7319714/Hyperlink_21.33_os3.zip)
[Hyperlink_21.33_os4.zip](https://github.com/amiga-mui/muidev/files/7319715/Hyperlink_21.33_os4.zip)
`
