### ISSUE TITLE
MUI splash popups off-centered

### ISSUE THREAD

**Issue by Andiweli** [amiga-mui/muidev#357]
Hello!

I've a strange problem here - was with MUI 3.8 and is still with MUI 5.0.
All splash popups of MUI programs are off-centered:

![IMG_3560](https://user-images.githubusercontent.com/11447150/153291142-ec70cf63-8845-46de-bfb8-042b4665aad8.jpeg)
![IMG_3559](https://user-images.githubusercontent.com/11447150/153291124-0ab03798-5e4f-4331-80dd-a96542f76f6a.jpeg)

I am using the "HiGFX" driver with HD720 monitor at a resolution of 1024x576.
If I use the standard PAL monitor at 1280x512 resolution, the splash popups are centered in the screen.

Did I miss some configuration setting or is this an error in MUI?

Kind regards
Andreas

**Comment by tboeckel** [comment]
It is hard to tell why the window is placed wrong depending on the screen resolution without knowing what the application itself sets/requests as the desired initial position. This would require either access to the source code (which I doubt you have) or a bit of debug output when it comes to how MUI calculates the initial window position/dimension.

**Comment by tboeckel** [comment]
[muimaster_22_227.zip](https://github.com/amiga-mui/muidev/files/8040970/muimaster_22_227.zip)
This an AmigaOS3 version of the latest released muimaster.library with some debug output added to the initial window dimension+position calculation. This output must be captured with tools like Sashimi. Please capture the output for a misbehaving application and attach it here.

**Comment by Andiweli** [comment]
[log.txt](https://github.com/amiga-mui/muidev/files/8041150/log.txt)

Thanks!
I've attached a Sashimi logfile - I started Genesis and Genesis Prefs (as in the screenshots above).

**Comment by tboeckel** [comment]
Here is your problem:
screen: w  1024, h   576, mx   675, my   540, bh    16
vpmode: ref 000B9024, refw  1280, refh   720

The screen's dimension and the dimensions of the screenmode do not match. In the end MUI will use the screenmode's dimensions to calculate the window position. But since the screenmode's dimension (1280x720) is larger than the screen's dimension (1024x576) the window will be shifted to the right and to the bottom.

To make it short: MUI is not guilty. It is your system which is using/providing inconsistent dimensions.

I am sorry, but there is nothing I can do against that.

**Comment by Andiweli** [comment]
Umm, so why not use the screen dimension instead of the screenmode?
Since AmigaOS offers the ability to give custom screen dimensions this is just fixable thru MUI.
