### ISSUE TITLE
Missing C:Installer

### ISSUE THREAD

**Issue by DidierMalenfant** [amiga-mui/muidev#364]
I'm trying to install MUI on a stock WB 3.2.2.1 and the installer is asking me for C:Installer.

Is this downloadable anywhere?

**Comment by tboeckel** [comment]
Since OS2.x C:Installer should be available on all systems and in all releases. There have been lots of more or less (in)compatible versions out in the wild, but the MUI Installer script should not exploit or depend on any fancy features of certain Installer versions.
I have no clue whether OS3.2.x includes C:Installer or not or if it may be located in a different directory. I never used OS3.2.x nor will I ever do. But I expect **all** applications from Aminet to rely on C:Installer being available, so this must exist on your system.

There are replacements available on Aminet, but I don't know how good they work at all:
- https://aminet.net/package/util/sys/InstallerNG
- https://aminet.net/package/util/wb/NewInstaller17

Fun fact: the replacements might require C:Installer to be available to install the replacement...

**Comment by DidierMalenfant** [comment]
That's odd because pretty much all other app like iBrowse or AmiGemini seem to find the standard installer just fine on that system.

But I guess you seem convinced that this is not an issue with MUI and that I don't need any more help so thanks for marking this as completed for me 😉

**Comment by DidierMalenfant** [comment]
In case this can help someone else, I did find the issue.

`Installer` is located in `Workbench:System` on my 3.2 install instead of `C:`. Other apps seem to deal with this by pointing simply to `Installer` instead of `C:Installer` and let PATH do its thing.

So the fix in this case is to edit the icon information for the MUI installer. Select `Install-MUI` and in the `Icon` menu select `Information` and then the `Icon` pane. Set `Default Tool` to just `Installer`.

**Comment by JohnArcher** [comment]
@DidierMalenfant Thanks a lot for sharing your solution. I had the exact same problem and could solve it because of your detailed explanation. 
So again, thanks a lot!
